### ISSUE TITLE
Unable to load the requested file: cp_main.php

### ISSUE THREAD

**Issue by carolinecblaker** [vector/VMG-Chosen-Member#16]
Attempting to enter Module prefs through Modules main screen, this error.

Just upgraded from 2.0, EE vers 2.9.2

**Comment by lukewilkins** [comment]
@carolinecblaker I've just tested this with EE 2.9.2 and don't appear to be receiving this error. Would you mind confirming that `third_party/vmg_chosen_member/views/cp_main.php` file exists within your project? If not, I recommend dropping in the `third_party/vmg_chosen_member` files once again from a [fresh download](https://github.com/vector/VMG-Chosen-Member/releases).

I'm not seeing any other reason for that error to be displaying currently, but if you continue to have issues, we'll definitely address further! Thanks.

**Comment by carolinecblaker** [comment]
You're absolutely right. It had been there all along - and I can offer nothing as to why it did not get uploaded, except for possible rumination on the concept of a lazy FTP client, if such exists. Thank you!
