### ISSUE TITLE
XMLHttpRequest CP issue

### ISSUE THREAD

**Issue by carolinecblaker** [vector/VMG-Chosen-Member#17]
Hi Team,

I'm getting: 

http://www.domain.org/?ACT=25032045&field_id=362&col_id=0&var_id=0. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://domain.org' is therefore not allowed access.

..when the add-on attempts to search for associated member accounts in the CP.

Seems like something I should be able to fix on my end.

Please advise & Thanks (& consider for your docs!)

**Comment by mrw** [comment]
Given the access control headers on your server, a good way to solve this is to check that the  Can you check that the `$base_url` in your config includes the www?

**Comment by carolinecblaker** [comment]
It looks like the CP URL and the Base URL were split, one WWW, one non-www.

This was an easy one. Thank you!
