### ISSUE TITLE
Member Field Defaulting To Entire List

### ISSUE THREAD

**Issue by shaunthompson** [vector/VMG-Chosen-Member#20]
Hi there, 

I'm encountering an issue where in creating a new entry with a VMG Chosen Member field, all members from the allowed group are selected by default. The member group as over 1,000 members so this makes it impractical to use.  If I edit an existing entry in the same channel, I can choose members and add them one by one. 

I've tried to find a setting or an option to change this, but I'm not seeing anything. Any help would be appreciated, thanks!

**Screenshot**

<img width="592" alt="screen shot 2016-08-30 at 3 05 13 pm" src="https://cloud.githubusercontent.com/assets/2948104/18103099/3d00603e-6ec3-11e6-88a2-09022ec9cc1d.png">

**Comment by mrw** [comment]
@shaunthompson Can you clarify what versions of EE, PHP, and VMG Chosen Member you're using?

**Comment by shaunthompson** [comment]
Absolutely – 

ExpressionEngine: 3.3.3
PHP: 5.6.21
VMG: I think this is the most recent, it's the branch you provided here: https://github.com/vector/VMG-Chosen-Member/tree/bugfix/18

**Comment by mrw** [comment]
Thanks @shaunthompson. I was able to recreate this issue and am assigning to @lukewilkins to take a look at. However, please note that he may not be able to get to it right away because we have some other client projects right now.

**Comment by shaunthompson** [comment]
Hi @mrw, thanks so much for the response. Appreciate you looking into it, totally understand about timing. Thanks!

**Comment by shaunthompson** [comment]
Hi @lukewilkins and @mrw, 

Following up to see if you've been able to take a look at this. If there's something I could test or try out, let me know. Appreciate your help, this plugin has been a life saver so far, excited to launch it with a new site. 

Thanks!

**Comment by mrw** [comment]
Unfortunately we haven't had time to look at this yet; hopefully we get time soon, but we're working on some client projects which we need to concentrate on at the moment.

**Comment by mrw** [comment]
@shaunthompson Just as a followup, we *may* be able to get this by the end of this week. We'll let you know!

**Comment by shaunthompson** [comment]
Thanks for the update @mrw!

**Comment by lukewilkins** [comment]
@shaunthompson This should now be resolved, and I apologize for the delay in getting around to correcting this. Let me know if you notice any other issues there.

https://github.com/vector/VMG-Chosen-Member/releases/tag/v3.0.2

**Comment by shaunthompson** [comment]
@lukewilkins Thank you so much Luke! No worries at all, really appreciate your help with this.
